text =" python programming "
print("Original:", text)
print("Lower:", text.lower())
print("Upper:", text.upper())
print("Strip:", text.strip())
print("Replace:", text.replace("Python", "Java"))
print("Find:", text.find("Program"))
print("Find:", text.find("Program"))
print("Count of 'm':", text.count("m"))
print("Starts with Python:", text.strip().startswith("Python"))
print("Ends with ing:", text.strip().endswith("ing"))